font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

font_size 12

foreground #cdd6f4
background #1e1e2e

cursor #f5e0dc

# transparency & blur (hyprland)
background_opacity 0.7

# padding
window_padding_width 10

# disable bell
enable_audio_bell no

# disable ligatures if you want
disable_ligatures never

# Smooth scrolling
scrollback_lines 5000

# Kitty theme colors (Catppuccin Mocha)
#include colors.conf
include ~/.config/wallust/colors-kitty.conf
shell zsh
