background #262524
foreground #FAF9F7

color0  #4C4B4A
color1  #D95F2A
color2  #73ACB6
color3  #ABA566
color4  #C79CBE
color5  #7AFB3A
color6  #F1EDE9
color7  #F0EEEC
color8  #A8A6A5
color9  #D95F2A
color10 #73ACB6
color11 #ABA566
color12 #C79CBE
color13 #7AFB3A
color14 #F1EDE9
color15 #F0EEEC
