exec-once = hyprpaper
exec-once = waybar & swaync & hypridle
# exec-once = dunst
exec-once = nm-applet
exec-once = swww init
exec-once = awww-daemon
exec-once = copyq
exec-once = mpd-mpris
exec-once = kanshi
exec-once = udiskie

# restore wallpaper 
exec-once = ~/.config/hypr/scripts/restore-wallpaper.sh
